# Generated by Django 5.1.3 on 2024-12-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminibadi', '0002_productvariants_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
