# Generated by Django 5.1.3 on 2024-12-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminibadi', '0003_product_product_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_offer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
