# Generated by Django 5.1.3 on 2024-12-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminibadi', '0004_category_category_offer_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_name', models.CharField(max_length=50, unique=True)),
                ('coupon_code', models.CharField(max_length=20, unique=True)),
                ('expiration_date', models.DateTimeField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('minimum_purchase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
    ]
