# Generated by Django 5.1.3 on 2024-12-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminibadi', '0006_coupon_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='expiration_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='maximum_discount_amount',
            new_name='maximum_discount',
        ),
    ]
