# Generated by Django 5.1.3 on 2024-12-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminibadi', '0007_rename_expiration_date_coupon_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_amount',
        ),
    ]
