# Generated by Django 5.1.3 on 2024-11-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0004_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
