# Generated by Django 5.1.3 on 2024-12-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0006_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
