# Generated by Django 5.1.3 on 2024-12-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0007_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
