# Generated by Django 5.1.3 on 2024-12-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0008_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
    ]
