# Generated by Django 5.1.3 on 2024-12-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0012_order_orderitem_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CNACELLED', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
