# Generated by Django 5.1.3 on 2024-12-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0013_remove_orderitem_order_status_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
