# Generated by Django 5.1.3 on 2024-12-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0015_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
