# Generated by Django 5.1.3 on 2024-12-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0016_order_net_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='net_amount',
        ),
    ]
