# Generated by Django 5.1.3 on 2024-12-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0017_remove_order_net_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
