# Generated by Django 5.1.3 on 2024-12-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0019_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
