# Generated by Django 5.1.3 on 2024-12-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0021_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
