# Generated by Django 5.1.3 on 2024-12-29 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminibadi', '0008_remove_coupon_discount_amount'),
        ('useribadi', '0022_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminibadi.coupon'),
        ),
    ]
