# Generated by Django 5.1.3 on 2024-12-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0023_order_coupon_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discounted_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
