# Generated by Django 5.1.3 on 2024-12-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0025_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN REQUESTED', 'Return Requested'), ('RETURNED', 'Returned'), ('RETURN REQUEST REJECTED', 'Return Request Rejected')], default='pending', max_length=50),
        ),
    ]
