# Generated by Django 5.1.3 on 2024-12-30 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0027_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment'), ('WALLET', 'Wallet Payment')], max_length=20),
        ),
    ]
