# Generated by Django 5.1.3 on 2024-12-30 15:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0028_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
