# Generated by Django 5.1.3 on 2025-01-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0029_wallet_transaction_id_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
