# Generated by Django 5.1.3 on 2025-01-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0031_alter_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
