# Generated by Django 5.1.3 on 2025-01-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0032_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
