# Generated by Django 5.1.3 on 2025-01-15 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useribadi', '0034_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='useribadi.order'),
        ),
    ]
