from django.urls import path
from . import views
from .views import userSignup

urlpatterns = [
    path('',views.index,name='index'),
    path('userSignup',views.userSignup,name='userSignup'),
    path('signupOtp',views.signupOtp,name='signupOtp'),
    path('userLogin',views.userLogin,name='userLogin'),
    path('userHome',views.userHome,name='userHome'),
    path('userLogout',views.userLogout,name='userLogout'),
    path('resendOtp',views.resendOtp,name='resendOtp'),
    path('forgotPassword',views.forgotPassword,name='forgotPassword'),
    path('forgotPasswordOtpVerify/<email>/',views.forgotPasswordOtpVerify,name='forgotPasswordOtpVerify'),
    path('resendOtpPassword/<str:email>',views.resendOtpPassword,name='resendOtpPassword'),
    path('resetPassword/<email>',views.resetPassword,name='resetPassword'),
    path('shop',views.shop,name='shop'),
    path('productPage/<int:product_id>/<int:variant_id>',views.productPage,name='productPage'),
    path('userProfile',views.userProfile,name='userProfile'),
    path('userProfile/edit/',views.editProfile,name='editProfile'),
    path('changePassword',views.changePassword,name='changePassword'),
    path('userAddress',views.userAddress,name='userAddress'),
    path('addAddress',views.addAddress,name='addAddress'),
    path('editAddress/<int:address_id>',views.editAddress,name='editAddress'),
    path('deleteAddress/<int:address_id>',views.deleteAddress,name='deleteAddress'),
    path('myCart',views.myCart,name='myCart'),
    path('addToCart/<int:product_id>',views.addToCart,name='addToCart'),
    path('removeFromCart/<int:product_id>',views.removeFromCart,name='removeFromCart'),
    path('checkoutPage',views.checkoutPage,name='checkoutPage'),
    path('updateCartQuantity/<int:product_id>',views.updateCartQuantity,name='updateCartQuantity'),
    path('myOrder',views.myOrder,name='myOrder'),
    path('removeProductFromOrder/<int:order_item_id>',views.removeProductFromOrder,name='removeProductFromOrder'),
    path('cancelOrder/<int:order_id>',views.cancelOrder,name='cancelOrder'),
    path('addToWishlist/<int:product_id>',views.addToWishlist,name='addToWishlist'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('removeFromWishlist/<int:product_id>',views.removeFromWishlist,name='removeFromWishlist'),
    path('wallet',views.wallet,name='wallet'),
]
